//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int cliente_id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string RNC { get; set; }
        public string calle { get; set; }
        public string no_casa { get; set; }
        public string sector { get; set; }
        public string ciudad { get; set; }
        public string provincia { get; set; }
        public Nullable<short> no_tarjeta { get; set; }
    
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
