//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public Oferta()
        {
            this.Venta_Ofertas = new HashSet<Venta_Ofertas>();
        }
    
        public int oferta_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_empieza { get; set; }
        public System.DateTime fecha_termina { get; set; }
        public int dias_disponible { get; set; }
        public System.TimeSpan hora_disponible_termina { get; set; }
        public Nullable<int> cantidad_maxima { get; set; }
        public Nullable<int> cantidad_minima { get; set; }
        public int producto_id { get; set; }
        public string tipo { get; set; }
        public System.TimeSpan hora_disponible_empieza { get; set; }
        public string codigo_cupon { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual OfertaPorciento OfertaPorciento { get; set; }
        public virtual ICollection<Venta_Ofertas> Venta_Ofertas { get; set; }
    }
}
