//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public Orden()
        {
            this.Orden_Productos = new HashSet<Orden_Productos>();
        }
    
        public int orden_id { get; set; }
        public int empleado_id { get; set; }
        public int suplidor_id { get; set; }
        public string NOTAS { get; set; }
        public Nullable<bool> aceptada { get; set; }
        public Nullable<System.DateTime> fecha_aceptada { get; set; }
        public Nullable<bool> despachada { get; set; }
        public Nullable<System.DateTime> fecha_despachada { get; set; }
        public Nullable<bool> recibida { get; set; }
        public Nullable<System.DateTime> fecha_recibida { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual ICollection<Orden_Productos> Orden_Productos { get; set; }
        public virtual Suplidor Suplidor { get; set; }
    }
}
