//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Ofertas = new HashSet<Oferta>();
            this.Orden_Productos = new HashSet<Orden_Productos>();
            this.RegistroInventario_Productos = new HashSet<RegistroInventario_Productos>();
            this.Venta_Productos = new HashSet<Venta_Productos>();
        }
    
        public int producto_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> etiqueta_negra { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
    
        public virtual ICollection<Oferta> Ofertas { get; set; }
        public virtual ICollection<Orden_Productos> Orden_Productos { get; set; }
        public virtual ICollection<RegistroInventario_Productos> RegistroInventario_Productos { get; set; }
        public virtual ICollection<Venta_Productos> Venta_Productos { get; set; }
        public virtual SaborHelado SaborHelado { get; set; }
    }
}
