//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroInventario
    {
        public RegistroInventario()
        {
            this.RegistroInventario_Productos = new HashSet<RegistroInventario_Productos>();
        }
    
        public int inventario_id { get; set; }
        public int empleado_id { get; set; }
        public string notas { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual ICollection<RegistroInventario_Productos> RegistroInventario_Productos { get; set; }
    }
}
