//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta_Ofertas
    {
        public long venta_id { get; set; }
        public int oferta_id { get; set; }
        public decimal rebaja { get; set; }
    
        public virtual Oferta Oferta { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
