//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Cajas = new HashSet<Caja>();
            this.RegistroInventarios = new HashSet<RegistroInventario>();
            this.Ordens = new HashSet<Orden>();
            this.Ventas = new HashSet<Venta>();
            this.Cajas1 = new HashSet<Caja>();
        }
    
        public int empleado_id { get; set; }
        public string no_identificacion { get; set; }
        public string tipo_identificacion { get; set; }
        public string correo { get; set; }
        public string password { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string calle { get; set; }
        public string no_casa { get; set; }
        public string sector { get; set; }
        public string ciudad { get; set; }
        public string provincia { get; set; }
        public Nullable<int> turno_id { get; set; }
        public string cargo { get; set; }
    
        public virtual ICollection<Caja> Cajas { get; set; }
        public virtual Turno Turno { get; set; }
        public virtual ICollection<RegistroInventario> RegistroInventarios { get; set; }
        public virtual ICollection<Orden> Ordens { get; set; }
        public virtual ICollection<Venta> Ventas { get; set; }
        public virtual ICollection<Caja> Cajas1 { get; set; }
    }
}
