//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class heladeriaEntities : DbContext
    {
        public heladeriaEntities()
            : base("name=heladeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Caja> Cajas { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Empleado> Empleadoes { get; set; }
        public DbSet<INFO> INFOes { get; set; }
        public DbSet<Oferta> Ofertas { get; set; }
        public DbSet<OfertaPorciento> OfertaPorcientoes { get; set; }
        public DbSet<Orden> Ordens { get; set; }
        public DbSet<Orden_Productos> Orden_Productos { get; set; }
        public DbSet<Producto> Productoes { get; set; }
        public DbSet<RegistroInventario> RegistroInventarios { get; set; }
        public DbSet<RegistroInventario_Productos> RegistroInventario_Productos { get; set; }
        public DbSet<SaborHelado> SaborHeladoes { get; set; }
        public DbSet<Suplidor> Suplidors { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Turno> Turnoes { get; set; }
        public DbSet<Venta> Ventas { get; set; }
        public DbSet<Venta_Ofertas> Venta_Ofertas { get; set; }
        public DbSet<Venta_Productos> Venta_Productos { get; set; }
        public DbSet<NCF> NCFs { get; set; }
    }
}
