//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCF
    {
        public string no_NCF { get; set; }
        public Nullable<long> venta_id { get; set; }
    
        public virtual Venta Venta { get; set; }
    }
}
