//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaborHelado
    {
        public int producto_id { get; set; }
        public Nullable<bool> temporal { get; set; }
        public Nullable<System.DateTime> principio_temporada { get; set; }
        public Nullable<System.DateTime> fin_temporada { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
