//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplidor
    {
        public Suplidor()
        {
            this.Ordens = new HashSet<Orden>();
            this.Productoes = new HashSet<Producto>();
        }
    
        public int suplidor_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string calle { get; set; }
        public string calle_no { get; set; }
        public string ciudad { get; set; }
        public string provincia { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<Orden> Ordens { get; set; }
        public virtual ICollection<Producto> Productoes { get; set; }
    }
}
